# Generated by Django 5.2.15 on 2026-06-04 21:05

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('auth_type', models.CharField(max_length=50)),
                ('credential_schema', models.JSONField(default=list)),
                ('available_resources', models.JSONField(default=list)),
                ('base_url', models.URLField(blank=True)),
                ('rate_limit_info', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('credentials', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_error', models.TextField(blank=True)),
                ('connector_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.connectortype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='tenants.tenant')),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TenantConnectorResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_slug', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('parameters', models.JSONField(default=dict)),
                ('sync_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('preload_from', models.DateField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_cursor', models.JSONField(blank=True, null=True)),
                ('total_records', models.IntegerField(default=0)),
                ('preview_data', models.JSONField(blank=True, null=True)),
                ('preview_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('preview_record_count', models.IntegerField(blank=True, null=True)),
                ('preview_fields', models.JSONField(blank=True, null=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='warehouse.tenantconnector')),
            ],
            options={
                'unique_together': {('connector', 'resource_slug')},
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('preview', 'Preview'), ('preload', 'Preload'), ('incremental', 'Incremental'), ('backfill', 'Backfill')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('records_fetched', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('sync_cursor_before', models.JSONField(blank=True, null=True)),
                ('sync_cursor_after', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('api_calls_made', models.IntegerField(default=0)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='warehouse.tenantconnectorresource')),
            ],
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('record_date', models.DateField(blank=True, db_index=True, null=True)),
                ('record_guid', models.CharField(blank=True, db_index=True, max_length=255)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector_resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='warehouse.tenantconnectorresource')),
            ],
            options={
                'indexes': [models.Index(fields=['connector_resource', 'record_date'], name='warehouse_r_connect_32aa70_idx'), models.Index(fields=['connector_resource', 'fetched_at'], name='warehouse_r_connect_e1a62c_idx'), django.contrib.postgres.indexes.GinIndex(fields=['data'], name='raw_record_data_gin')],
                'unique_together': {('connector_resource', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='MaterializedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('query', models.TextField()),
                ('auto_refresh', models.BooleanField(default=True)),
                ('cache_table_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('error', 'Error')], default='draft', max_length=20)),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('refresh_duration_ms', models.IntegerField(blank=True, null=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('depends_on_views', models.ManyToManyField(blank=True, related_name='downstream_views', to='warehouse.materializedview')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materialized_views', to='tenants.tenant')),
                ('depends_on_resources', models.ManyToManyField(blank=True, related_name='downstream_views', to='warehouse.tenantconnectorresource')),
            ],
            options={
                'unique_together': {('tenant', 'slug')},
            },
        ),
    ]
