# Generated by Django 5.2.15 on 2026-06-04 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantconnectorresource',
            name='api_path',
            field=models.CharField(blank=True, help_text='API endpoint path, e.g. /api/contracts', max_length=500),
        ),
        migrations.AddField(
            model_name='tenantconnectorresource',
            name='cursor_field',
            field=models.CharField(blank=True, help_text='Date field for incremental sync', max_length=200),
        ),
        migrations.AddField(
            model_name='tenantconnectorresource',
            name='custom_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tenantconnectorresource',
            name='dependent_path_template',
            field=models.CharField(blank=True, help_text='Path template, e.g. /api/contracts/{guid}/details', max_length=500),
        ),
        migrations.AddField(
            model_name='tenantconnectorresource',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='warehouse.tenantconnectorresource'),
        ),
        migrations.AddField(
            model_name='tenantconnectorresource',
            name='depends_on_column',
            field=models.CharField(blank=True, help_text='Column from parent resource to use as parameter', max_length=200),
        ),
        migrations.AddField(
            model_name='tenantconnectorresource',
            name='id_field',
            field=models.CharField(blank=True, help_text='Unique ID field in response', max_length=200),
        ),
        migrations.AddField(
            model_name='tenantconnectorresource',
            name='notes',
            field=models.TextField(blank=True, help_text='Context notes for AI processing'),
        ),
    ]
